apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jpm2cytky-dotnet-basic 
  janus-idp.io/tekton: jpm2cytky-dotnet-basic
  backstage.io/kubernetes-id: jpm2cytky-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jpm2cytky-dotnet-basic
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml